__title__ = "compas_plotter"
__description__ = "2D visualisation of COMPAS geometry and data structures with matplotlib."
__url__ = "https://github.com/compas-dev/compas_plotter"
__version__ = "1.0.0-rc0"
__author__ = "tom van mele"
__author_email__ = "tom.v.mele@gmail.com"
__license__ = "MIT license"
__copyright__ = "Copyright 2017-2026 ETH Zurich"
